"""Initial migration

Revision ID: 44beb4c30946
Revises: 
Create Date: 2022-07-24 02:27:02.133561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44beb4c30946'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('party_size', sa.Integer(), nullable=False))
    op.add_column('profile', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.drop_column('profile', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('age', sa.INTEGER(), nullable=False))
    op.drop_column('profile', 'phone_number')
    op.drop_column('profile', 'party_size')
    # ### end Alembic commands ###
